### ISSUE TITLE
// from 与 //to 构造 SipURI 都使用 设备deviceId问题

### ISSUE THREAD

**Issue by angelshowzhe** [swwheihei/wvp#5]
是这样的,今天调试视频直播接口为 /api/play/{deviceId}/{channelId} 在
invite,createInviteRequest(SIPRequestHeaderProvider.java line 74) //from 与 //to 构造SipURI 时候 因为都采用了device.getDeviceId() 也就是设备id导致 视频不能播放 ,后来 我在//to的地方 传递 channelId ,可以播放摄像头视频了 但是 报了一个
javax.sip.SipException: Cannot create ACK - no remote Target!
at gov.nist.javax.sip.stack.SIPDialog.createAck(SIPDialog.java:3122)
at com.genersoft.iot.vmp.gb28181.transmit.response.impl.InviteResponseProcessor.process(InviteResponseProcessor.java:33)
at com.genersoft.iot.vmp.gb28181.SipLayer.processResponse(SipLayer.java:129)
at gov.nist.javax.sip.EventScanner.deliverResponseEvent(EventScanner.java:317)
at gov.nist.javax.sip.EventScanner.deliverEvent(EventScanner.java:148)
at gov.nist.javax.sip.EventScanner.run(EventScanner.java:513)
at java.lang.Thread.run(Thread.java:748)
----------------------------------------------------------------------------------
后来我直接注册设备,就不会报上面的错,注册下级平台会报

**Comment by swwheihei** [comment]
我用我们设备测试没有问题呢。今天对于底层通信改动不少，你更新下代码试试。
现在还不支持平台级联呢
